/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class DemoC */

#ifndef _Included_DemoC
#define _Included_DemoC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     DemoC
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_DemoC_sayHello
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
